import type { SizeKey } from './enums/size';
import type { RoundedKey } from './enums/rounded';
import type { FillModeKey } from './enums/fillmode';
import type { ThemeColorKey } from './enums/themecolor';
export declare class KendoDropDownList extends HTMLInputElement {
    private wrapperPrefix;
    private roundedPrefix;
    private _dataSource;
    private _rendered?;
    private _value?;
    private _text?;
    private _optionLabel?;
    private _dataTextField;
    private _dataValueField;
    private _size;
    private _rounded;
    private _fillMode;
    private _themeColor;
    private _list;
    private _button;
    private _popup;
    private _inputValue;
    wrapper?: HTMLElement;
    private ariaLabel?;
    set dataSource(val: any);
    get dataSource(): any;
    set value(val: any);
    get value(): any;
    set text(val: any);
    get text(): any;
    set optionLabel(val: string);
    get optionLabel(): string;
    set dataTextField(val: string);
    get dataTextField(): string;
    set dataValueField(val: string);
    get dataValueField(): string;
    get size(): SizeKey;
    set size(value: SizeKey);
    get rounded(): RoundedKey;
    set rounded(value: RoundedKey);
    get fillMode(): FillModeKey;
    set fillMode(value: FillModeKey);
    get themeColor(): ThemeColorKey;
    set themeColor(value: ThemeColorKey);
    constructor();
    connectedCallback(): void;
    events(): void;
    render(): void;
    disconnectedCallback(): void;
    signal(prop: string, newValue: string, oldValue: string): void;
    private _ariaLabel;
    private _createButton;
    private _createInput;
    private _createList;
    private _createPopup;
    private _generateLabelId;
    private _validateValue;
    private _validateText;
}
